#
# Module manifest for module 'nvm-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    RootModule    = 'nvm-tab-completion.psm1'

    ModuleVersion = '1.0.1'

    GUID          = '8336c830-4e3d-4fa6-a687-6f3d5156fda9'

    Author        = 'abgo'

    Copyright     = '(c) abgo. All rights reserved.'

    Description   = 'nvm(nvm-window) tab completion.Support-DIY(do-it-yourself) by editing JSON. For more information, please visit the project: https://github.com/abgox/PS-completions'

    PrivateData   = @{

        PSData = @{

            Tags       = @('nvm', 'nvm-window','tab', 'completion', 'tab-comletion', 'Support-DIY(do-it-yourself)')

            LicenseUri = 'https://github.com/abgox/PS-completions/blob/main/LICENSE'

            ProjectUri = 'https://github.com/abgox/PS-completions'
        }

    }
}
