#
# Module manifest for module 'chfs-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/10
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule    = 'chfs-tab-completion.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # ID used to uniquely identify thxis module
    GUID          = '9b970e32-477e-4e78-9d0b-bf2802d3f4ba'

    # Author of this module
    Author        = 'abgo'

    # Company or vendor of this module
    CompanyName   = 'Unknown'

    # Copyright statement for this module
    Copyright     = '(c) abgo. All rights reserved.'

    # Description of the functionality provided by this module
    Description   = 'chfs tab completion'
}

