#
# Module manifest for module 'chfs-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/10
#

@{

    RootModule    = 'chfs-tab-completion.psm1'

    ModuleVersion = '1.2.2'

    GUID          = '9b970e32-477e-4e78-9d0b-bf2802d3f4ba'

    Author        = 'abgo'

    Copyright     = '(c) abgo. All rights reserved.'

    Description   = 'chfs(CuteHttpFileServer) tab completion.Support-DIY(do-it-yourself) by editing JSON. For more information, please visit the project: https://github.com/abgox/PS-completions'

    PrivateData   = @{

        PSData = @{

            Tags       = @('chfs', 'tab', 'completion', 'tab-comletion', 'Support-DIY(do-it-yourself)')

            LicenseUri = 'https://github.com/abgox/PS-completions/blob/main/LICENSE'

            ProjectUri = 'https://github.com/abgox/PS-completions'

        }

    }
}

