#
# Module manifest for module '{{ project_name }}'
#
# Generated by: {{ author }}
#
# Generated on: {{ current_date_str }}
#

@{

    RootModule    = '{{ project_name }}.psm1'

    ModuleVersion = '1.0.0'

    GUID          = '{{ guid }}'

    Author        = '{{ author }}'

    Copyright     = '{{ copyright }}'

    Description   = '{{ description }}'

    PrivateData   = @{

        PSData = @{

            Tags       = @({{ tags_str }})

            LicenseUri = '{{ license_uri}}'

            ProjectUri = '{{ project_uri }}'

        }

    }
}
