#
# Module manifest for module 'python-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    RootModule    = 'python-tab-completion.psm1'

    ModuleVersion = '1.1.0'

    GUID          = '895a755a-8101-44aa-b9f7-eb7ce483e033'

    Author        = 'abgo'

    Copyright     = '(c) abgo. All rights reserved.'

    Description   = 'Python tab completion.The data of completion comes from json,and you can modify the json file to change the completion as required. For more information, please visit the project: https://github.com/abgox/PS-completions'

    PrivateData   = @{

        PSData = @{

            Tags       = @('python', 'tab', 'completion', 'tab-comletion', 'Multi-language')

            LicenseUri = 'https://github.com/abgox/PS-completions/blob/main/LICENSE'

            ProjectUri = 'https://github.com/abgox/PS-completions'

        }

    }
}
