#
# Module manifest for module 'npm-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    RootModule    = 'npm-tab-completion.psm1'

    ModuleVersion = '1.3.1'

    GUID          = '8db3df6c-39f9-4fb6-bcc6-eee6a15926fe'

    Author        = 'abgo'

    Copyright     = '(c) abgo. All rights reserved.'

    Description   = 'npm tab completion.The data of completion comes from json,and you can modify the json file to change the completion as required. For more information, please visit the project: https://github.com/abgox/PS-completions'

    PrivateData   = @{

        PSData = @{

            Tags       = @('npm', 'tab', 'completion', 'tab-comletion','Multi-language')

            LicenseUri = 'https://github.com/abgox/PS-completions/blob/main/LICENSE'

            ProjectUri = 'https://github.com/abgox/PS-completions'

        }

    }
}
