#
# Module manifest for module 'pnpm-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    RootModule    = 'pnpm-tab-completion.psm1'

    ModuleVersion = '1.1.2'

    GUID          = 'c2d26e68-f6b1-4370-b35c-411ff9e614d9'

    Author        = 'abgo'

    Copyright     = '(c) abgo. All rights reserved.'

    Description   = 'pnpm tab completion.Support-DIY(do-it-yourself) by editing JSON. For more information, please visit the project: https://github.com/abgox/PS-completions'

    ScriptsToProcess = @("json_download.ps1")

    PrivateData   = @{

        PSData = @{

            Tags       = @('pnpm', 'tab', 'completion', 'tab-comletion', 'Support-DIY(do-it-yourself)')

            LicenseUri = 'https://github.com/abgox/PS-completions/blob/main/LICENSE'

            ProjectUri = 'https://github.com/abgox/PS-completions'

        }

    }
}
