#
# Module manifest for module 'pnpm-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule    = 'pnpm-tab-completion.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # ID used to uniquely identify this module
    GUID          = 'c2d26e68-f6b1-4370-b35c-411ff9e614d9'

    # Author of this module
    Author        = 'abgo'

    # Company or vendor of this module
    CompanyName   = 'Unknown'

    # Copyright statement for this module
    Copyright     = '(c) abgo. All rights reserved.'

    # Description of the functionality provided by this module
    Description   = 'pnpm tab completion'
}

