#
# Module manifest for module 'volta-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule    = 'volta-tab-completion.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.2'

    # ID used to uniquely identify this module
    GUID          = 'fc4639d8-7bc8-41da-ae8f-d38fc4b90890'

    # Author of this module
    Author        = 'abgo'

    # Company or vendor of this module
    CompanyName   = 'Unknown'

    # Copyright statement for this module
    Copyright     = '(c) abgo. All rights reserved.'

    # Description of the functionality provided by this module
    Description   = 'volta tab completion'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData   = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('volta', 'tab', 'completion','tab-comletion')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/abgox/PS-completions/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/abgox/PS-completions'

        } # End of PSData hashtable

    }# End of PrivateData hashtable
}

