#
# Module manifest for module 'volta-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule    = 'volta-tab-completion.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.1'

    # ID used to uniquely identify this module
    GUID          = 'fc4639d8-7bc8-41da-ae8f-d38fc4b90890'

    # Author of this module
    Author        = 'abgo'

    # Company or vendor of this module
    CompanyName   = 'Unknown'

    # Copyright statement for this module
    Copyright     = '(c) abgo. All rights reserved.'

    # Description of the functionality provided by this module
    Description   = 'volta tab completion'
}

