#
# Module manifest for module 'volta-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    RootModule    = 'volta-tab-completion.psm1'

    ModuleVersion = '1.2.1'

    GUID          = 'fc4639d8-7bc8-41da-ae8f-d38fc4b90890'

    Author        = 'abgo'

    Copyright     = '(c) abgo. All rights reserved.'

    Description   = 'Volta tab completion.The data of completion comes from json,and you can modify the json file to change the completion as required. For more information, please visit the project: https://github.com/abgox/PS-completions'

    PrivateData   = @{

        PSData = @{

            Tags       = @('volta', 'tab', 'completion', 'tab-comletion', 'Multi-language')

            LicenseUri = 'https://github.com/abgox/PS-completions/blob/main/LICENSE'

            ProjectUri = 'https://github.com/abgox/PS-completions'

        }

    }
}

