#
# Module manifest for module 'scoop-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule    = 'scoop-tab-completion.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.2'

    # ID used to uniquely identify this module
    GUID          = 'ab913566-0cf9-47d1-a92f-6649820696d6'

    # Author of this module
    Author        = 'abgo'

    # Company or vendor of this module
    CompanyName   = 'Unknown'

    # Copyright statement for this module
    Copyright     = '(c) abgo. All rights reserved.'

    # Description of the functionality provided by this module
    Description   = 'Scoop tab completion'
}

