#
# Module manifest for module 'scoop-tab-completion'
#
# Generated by: abgo
#
# Generated on: 2023/6/9
#

@{

    RootModule    = 'scoop-tab-completion.psm1'

    ModuleVersion = '1.1.2'

    GUID          = 'ab913566-0cf9-47d1-a92f-6649820696d6'

    Author        = 'abgo'

    Copyright     = '(c) abgo. All rights reserved.'

    Description   = 'scoop tab completion.Support-DIY(do-it-yourself) by editing JSON. For more information, please visit the project: https://github.com/abgox/PS-completions'

    PrivateData   = @{

        PSData = @{

            Tags       = @('scoop', 'tab', 'completion', 'tab-comletion', 'Support-DIY(do-it-yourself)')

            LicenseUri = 'https://github.com/abgox/PS-completions/blob/main/LICENSE'

            ProjectUri = 'https://github.com/abgox/PS-completions'

        }

    }
}
